label: bcic_iv_2a
name: moabb
dataset_name: BNCI2014_001
data_dir: data/moabb
subject_ids:
  - 3
split:
  strategy: session_train_test
  session:
    column: session
    train_key: 0train
    test_key: 1test
  validation:
    valid_size: 0.2
    shuffle: false
  resampling:
    method: kfold # kfold or holdout
    n_splits: 5
    valid_size: 0.2
    shuffle: false
mapping:
  left_hand: 0
  right_hand: 1
  feet: 2
  tongue: 3
