name: moabb
dataset_name: BNCI2014_001
data_dir: data/moabb
subject_ids:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
split:
  strategy: session_cross_validation_test
  session:
    column: session
    train_key: 0train
    test_key: 1test
  validation:
    valid_size: 0.2
    shuffle: false
  resampling:
    method: kfold # kfold or holdout
    n_splits: 5
    shuffle: false
mapping:
  left_hand: 0
  right_hand: 1
  feet: 2
  tongue: 3
