label: liu2024
name: moabb
dataset_name: Liu2024
data_dir: data/moabb
subject_ids:
  - 1
split:
  source: chronological
  method: train_test
  test_size: 0.2
  stratify: true
  validation:
    valid_size: 0.2
    shuffle: false
  resampling:
    method: holdout # kfold or holdout
    n_splits: 5
    shuffle: false
mapping:
  left_hand: 0
  right_hand: 1
